[package]
name         = "bos-algo"
version      = "0.1.0"
edition      = "2024"
rust-version = "1.85"

[dependencies]
rand       = "0.9"
clap       = { version = "4.2", features = ["derive"] }
reqwest    = { version = "0.11", features = ["blocking", "json"] }
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
proptest = "1.4"

[lib]
name = "bos_algo"
path = "src/lib.rs"

[[bin]]
name = "sim"
path = "src/bin/sim.rs"
