[package]
name    = "bos-algo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
rand = "0.9.1"

[dev-dependencies]
proptest = "1.4"

[lib]
name = "bos_algo"
path = "src/lib.rs"

[[bin]]
name = "sim"
path = "src/bin/sim.rs"
