codecov:
  require_ci_to_pass: yes
  max_report_age: 24

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        flags:
          - unit
        paths:
          - "src"
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "examples/**/*"
  - "src/bin/**/*"
  - "artifacts/**/*"